# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-30 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URLTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='No name', max_length=50)),
            ],
            options={
                'verbose_name': 'URL Table',
            },
        ),
    ]
